-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 18:09:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vol` DEFAULT CHARACTER SET utf8 ;
USE `vol` ;

-- -----------------------------------------------------
-- Table `vol`.`aeroport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`aeroport` (
  `nom` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vol`.`vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`vol` (
  `idvol` INT NOT NULL,
  `date depart` DATE NULL,
  `date retour` DATE NULL,
  `heure depart/retour` VARCHAR(30) NULL,
  `prix` VARCHAR(10) NULL,
  `ville` VARCHAR(30) NULL,
  `aeroport_nom` VARCHAR(10) NOT NULL,
  `aeroport_nom1` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idvol`),
  CONSTRAINT `fk_vol_aeroport1`
    FOREIGN KEY (`aeroport_nom`)
    REFERENCES `vol`.`aeroport` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vol_aeroport2`
    FOREIGN KEY (`aeroport_nom1`)
    REFERENCES `vol`.`aeroport` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vol_aeroport1_idx` ON `vol`.`vol` (`aeroport_nom` ASC) VISIBLE;

CREATE INDEX `fk_vol_aeroport2_idx` ON `vol`.`vol` (`aeroport_nom1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vol`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`reservation` (
  `id reservation` INT NOT NULL,
  `date` DATE NULL,
  `nb place` INT NULL,
  `vol_idvol` INT NOT NULL,
  PRIMARY KEY (`id reservation`, `vol_idvol`),
  CONSTRAINT `fk_reservation_vol1`
    FOREIGN KEY (`vol_idvol`)
    REFERENCES `vol`.`vol` (`idvol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reservation_vol1_idx` ON `vol`.`reservation` (`vol_idvol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vol`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`compte` (
  `idcompte` INT NOT NULL,
  `libelle compte` VARCHAR(30) NULL,
  PRIMARY KEY (`idcompte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vol`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`client` (
  `cin` VARCHAR(10) NOT NULL,
  ` nom et prenom` VARCHAR(30) NULL,
  `date de naissance` DATE NULL,
  `tel` VARCHAR(10) NULL,
  `email` VARCHAR(30) NULL,
  `psw` VARCHAR(10) NULL,
  `reservation_id reservation` INT NOT NULL,
  `compte_idcompte` INT NOT NULL,
  PRIMARY KEY (`cin`, `compte_idcompte`),
  CONSTRAINT `fk_client_reservation`
    FOREIGN KEY (`reservation_id reservation`)
    REFERENCES `vol`.`reservation` (`id reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_compte1`
    FOREIGN KEY (`compte_idcompte`)
    REFERENCES `vol`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_reservation_idx` ON `vol`.`client` (`reservation_id reservation` ASC) VISIBLE;

CREATE INDEX `fk_client_compte1_idx` ON `vol`.`client` (`compte_idcompte` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vol`.`compagnie aerienne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vol`.`compagnie aerienne` (
  `id ca` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `vol_idvol` INT NOT NULL,
  PRIMARY KEY (`id ca`),
  CONSTRAINT `fk_compagnie aerienne_vol1`
    FOREIGN KEY (`vol_idvol`)
    REFERENCES `vol`.`vol` (`idvol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compagnie aerienne_vol1_idx` ON `vol`.`compagnie aerienne` (`vol_idvol` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
